apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-app-050111
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/neworgyangcao/go-app-050111:5993b8ca1e4215c7012f1dffe4206f49042d27ef@sha256:d601580a60d62e4ac7faeefa07c02b2dc7084e45030c03fca367a4d1a7368d94
          name: container-image
